Keep retention (#2)
* updated zf_zpool_has_feature zpool command

* added zf_zfs_destroy

* implemented -k and -K

* apply retention after deciding to sync or not

* added zf_zfs_apply_retention for applying local and remote retention

* check for destroy permission before applying retention

* retention can be given in periods of time

* added defaults to zfsync.conf

* fixed regression and optimized sending initial snapshot

* removed redundant check

* updated documentation

diff --git a/lib/zfs b/lib/zfs
--- a/lib/zfs
+++ b/lib/zfs
@@ -97,7 +97,7 @@ zf_zfs_matching_snapshots() {
     printf "%s\n" $(zf_zfs_snapshots "${remote_zfs}" 1) > ${tmp_remote}
 
     # show matches
-    comm -12 ${tmp_local} ${tmp_remote}
+    comm -12 ${tmp_local} ${tmp_remote} || true
     rm ${tmp_local} ${tmp_remote}
 }
 
@@ -181,6 +181,89 @@ zf_zfs_sync() {
     # TODO: perhaps not always use -F
     zf_zfs_cmd "send ${options} ${source} ${send_pipe_arg}" | \
         zf_zfs_remote_cmd "zfs receive -F ${target} ${recv_pipe_arg}"
+}
+
+zf_zfs_destroy() {
+    local filesystem=$1 snapshot=$2 remote=$3 cmd
+    [ -z "${filesystem}" -o -z "${snapshot}" ] && zf_error "zf_zfs_destroy requires filesystem and snapshot parameter"
+
+    echo ${snapshot} | grep -q '^@' || zf_error "snapshot should start with @: ${snapshot}"
+
+    zf_zfs_exists "${filesystem}${snapshot}" $remote || zf_error "snapshot ${filesystem}${snapshot} doesn't exists"
+
+    cmd="destroy ${filesystem}${snapshot}"
+    if [ "${remote}" = 1 ]; then
+        zf_zfs_remote_cmd "${cmd}"
+    else
+        zf_zfs_cmd "${cmd}"
+    fi
+}
+
+zf_zfs_apply_retention() {
+    local filesystem=$1 retention=$2 limit=$3 user=$4 remote=$5 snapshots count
+    [ -z "${filesystem}" -o -z "${retention}" -o -z "${limit}" -o -z "${user}" ] && zf_error "zf_zfs_apply_retention requires filesystem, retention, limit and user parameter"
+
+    echo ${retention} | grep -Eq '^[0-9]+(h|H|d|w|m)?$' || zf_error "retention should be given numerically, optionally followed with a time unit h, d, w or m"
+
+    if ! zf_zfs_is_user_allowed "${user}" "destroy" "${filesystem}" ${remote}; then
+        zf_warn "not keeping retention, user ${user} has no destroy permission on ${filesystem}"
+        return
+    fi
+
+    snapshots=$(zf_zfs_snapshots ${filesystem} ${remote})
+    [ -z "${snapshots}" ] && zf_error "no snapshots found for ${filesystem}"
+    count=$(echo ${snapshots} | wc -w | awk '{print $1}')
+
+    # try to determine which time unit is given
+    retterm=$(echo ${retention} | grep -Eo '(h|H|d|w|m)$')
+    if [ ${?} -eq 0 ]; then
+        retention=$(echo ${retention} | grep -Eo '^[0-9]+')
+        local timeout
+        case ${retterm} in
+            [hH]) timeout=$(date -v-${retention}H "+%s");;
+            [dwm]) timeout=$(date -v-${retention}${retterm} "+%s");;
+            *) zf_error "invalid time unit ${retterm}";;
+        esac
+
+        zf_debug "based on given retention, timeout set to: ${timeout} ($(date -r ${timeout}))"
+        local snapshot snapshot_creation time_retention=0
+        for snapshot in ${snapshots}; do
+            cmd="get -H -p -o value creation ${filesystem}${snapshot}"
+            if [ "${remote}" = 1 ]; then
+                snapshot_creation=$(zf_zfs_remote_cmd "${cmd}")
+            else
+                snapshot_creation=$(zf_zfs_cmd "${cmd}")
+            fi
+            [ -z "${snapshot_creation}" ] && zf_error "could not get creation for ${filesystem}${snapshot}"
+            [ ${snapshot_creation} -ge ${timeout} ] && zf_debug "${filesystem}${snapshot}, created on ${snapshot_creation}, exceeds timeout ${timeout}" && break
+            time_retention=$((time_retention + 1))
+        done
+
+        zf_debug "based on retention of ${retention}${retterm}, ${time_retention} snapshots will be removed"
+        retention=$((count - time_retention))
+    fi
+
+    zf_msg "Applying retention of ${retention} snapshots to ${filesystem}"
+    if [ ${count} -le ${retention} ]; then
+        zf_debug "number of snapshots (${count}) below or equal to desired retention (${retention})"
+        return 0
+    fi
+
+    zf_debug "$((count - retention)) snapshots will be removed"
+
+    for snapshot in ${snapshots}; do
+        if [ "${snapshot}" = "${limit}" ]; then
+            zf_warn "not removing last match ${limit} or beyond, since this would break replication"
+            break
+        fi
+
+        zf_zfs_destroy ${filesystem} ${snapshot} ${remote}
+        count=$((count - 1))
+        if [ "${count}" -le "${retention}" ]; then
+            zf_msg "${filesystem} kept at ${count} snapshots"
+            break
+        fi
+    done
 }
 
 fi
